language: python
os:
  - linux
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
branches:
  only:
    - master
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=ratcave setup.py test
after_success:
  coveralls